
TARGET=colorer.exe
all: $(TARGET)

CYGWIN=-mno-cygwin

shared_path=../shared/
obj_output=objs

include ../shared/makefile.colorer.cygwin

LIBINC = -lwininet -lstdc++
LIBFLAGS = $(objs) $(FLAGS) -o $(TARGET) $(LIBINC)

include makefile.core

clean:
	$(RM) $(objs)
