
TARGET=colorer.exe
all: $(TARGET)

CYGWIN=-mno-cygwin

shared_path=../shared/
obj_output=objs

include ../shared/makefile.colorer.cygwin

LIBINC = -lwininet -lstdc++ -lmingw32
LIBFLAGS = $(objs) $(FLAGS) -o $(TARGET) $(LIBINC)
CPPFLAGS_CUSTOM =  -g 
#-DCOLORER_FEATURE_LOGLEVEL=COLORER_FEATURE_LOGLEVEL_FULL -DCOLORER_FEATURE_ASSERT=TRUE

include makefile.core

clean:
	$(RM) $(objs)
