
all: pcolorer.o FarEditorSet.o FarEditor.o
	perl ../shared/_makefile.deps.pl
	rm -f *.d *.o ".o"

#generate dependencies:
CPPFLAGS_CUSTOM=-MD -E

shared_path=../shared/
obj_output=.

include ../shared/makefile.colorer.gcc

pcolorer.o: pcolorer.cpp
	$(CPP) $(CPPFLAGS) pcolorer.cpp

FarEditorSet.o: FarEditorSet.cpp
	$(CPP) $(CPPFLAGS) FarEditorSet.cpp

FarEditor.o: FarEditor.cpp
	$(CPP) $(CPPFLAGS) FarEditor.cpp

clean:
	$(RM) $(objs)
