
all: colorer.dll

shared_path=../shared/
obj_output=objs

!include $(shared_path)makefile.colorer.bcc
!include _dependencies.dep
!include makefile.core

LIBFLAGS = /Tpd $(objs) -L"C:\Program Files\Borland\bcc55\lib" c0d32.obj, colorer.dll, ,import32.lib wininet.lib cw32.lib

colorer.dll: $(objs)
	$(LINK) $(LIBFLAGS)

clean:
	$(RM) $(objs) colorer.map colorer.il? colorer.tds
